# Generated by Django 6.0.8 on 2026-09-23 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_cafeprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafeprofile',
            name='google_maps_url',
            field=models.URLField(blank=True, max_length=2048),
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='avatars/people/'),
        ),
    ]
