# Generated by Django 6.0.8 on 2026-09-24 16:59

import accounts.models
import django.db.models.deletion
from django.db import migrations, models
import uuid


def assign_public_ids(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    for user in User.objects.using(schema_editor.connection.alias).all().iterator():
        User.objects.using(schema_editor.connection.alias).filter(pk=user.pk).update(public_id=uuid.uuid4().hex)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_cafeprofile'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('walks', '0003_activity_foundations'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_walk_session',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_for_user', to='walks.walksession'),
        ),
        migrations.AddField(
            model_name='user',
            name='auth_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='leaderboard_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='location_visibility',
            field=models.CharField(choices=[('OFF', 'Off'), ('FRIENDS', 'Friends')], default='OFF', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='net_matching_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='notification_preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='user',
            name='public_id',
            field=models.CharField(editable=False, max_length=32, unique=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='virtual_avatar_key',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('location_visibility__in', ('OFF', 'FRIENDS'))), name='user_location_visibility_known'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('auth_version__gt', 0)), name='user_auth_version_positive'),
        ),
        migrations.RunPython(assign_public_ids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user', name='public_id',
            field=models.CharField(default=accounts.models.new_public_id, editable=False, max_length=32, unique=True),
        ),
    ]
