# Generated by Django 6.0.8 on 2026-09-23 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='uploaded_photo',
            field=models.FileField(blank=True, upload_to='avatars/dogs/'),
        ),
    ]
