# Generated by Django 6.0.8 on 2026-09-24 15:09

import dogs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0002_dog_uploaded_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, validators=[dogs.models.validate_birth_date]),
        ),
    ]
