# Generated by Django 6.0.8 on 2026-09-24 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '__first__'),
        ('dogs', '0003_dog_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='microchip_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dog',
            name='microchip_recorded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dog',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DogDailyGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_goals', to='dogs.dog')),
                ('dog_id_snapshot', models.BigIntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dog_daily_goals', to=settings.AUTH_USER_MODEL)),
                ('local_date', models.DateField()),
                ('target_active_seconds', models.PositiveIntegerField()),
                ('inputs_snapshot', models.JSONField()),
                ('rules_version', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finalised_at', models.DateTimeField(blank=True, null=True)),
                ('final_active_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('final_goal_met', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['owner', 'local_date'], name='dog_goal_owner_date')],
                'constraints': [models.UniqueConstraint(fields=('dog_id_snapshot', 'local_date'), name='dog_goal_date_unique'), models.CheckConstraint(condition=models.Q(('dog_id_snapshot__gt', 0)), name='dog_goal_identity_positive'), models.CheckConstraint(condition=models.Q(('target_active_seconds__gt', 0)), name='dog_goal_target_positive'), models.CheckConstraint(condition=models.Q(models.Q(('final_active_seconds__isnull', True), ('final_goal_met__isnull', True), ('finalised_at__isnull', True)), models.Q(('final_active_seconds__isnull', False), ('final_goal_met__isnull', False), ('finalised_at__isnull', False), models.Q(models.Q(('final_active_seconds__gte', models.F('target_active_seconds')), ('final_goal_met', True)), models.Q(('final_active_seconds__lt', models.F('target_active_seconds')), ('final_goal_met', False)), _connector='OR')), _connector='OR'), name='dog_goal_final_result_shape')],
            },
        ),
    ]
