# Generated by Django 6.0.8 on 2026-10-04 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0004_dog_daily_goal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DogGoalTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_id_snapshot', models.BigIntegerField(editable=False)),
                ('effective_from', models.DateField()),
                ('target_active_seconds', models.PositiveIntegerField(blank=True, help_text='Approved daily walking seconds. Leave empty to pause goals; no default formula.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goal_targets', to='dogs.dog')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('effective_from', 'pk'),
                'constraints': [models.UniqueConstraint(fields=('dog_id_snapshot', 'effective_from'), name='dog_target_effective_unique'), models.CheckConstraint(condition=models.Q(('dog_id_snapshot__gt', 0)), name='dog_target_identity_positive'), models.CheckConstraint(condition=models.Q(('target_active_seconds__isnull', True), ('target_active_seconds__gt', 0), _connector='OR'), name='dog_target_positive')],
            },
        ),
    ]
