# Generated by Django 6.0.8 on 2026-10-05 21:34

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0006_goal_owner_versions'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='doggoaltarget',
            name='calculation_inputs',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='doggoaltarget',
            name='calculation_policy',
            field=models.CharField(default='manual-duration-v1', editable=False, max_length=40),
        ),
        migrations.AlterField(
            model_name='breed',
            name='energy_level',
            field=models.CharField(choices=[('LOW', 'Low'), ('MODERATE', 'Moderate'), ('HIGH', 'High'), ('VERY_HIGH', 'Very high'), ('UNKNOWN', 'Unknown')], max_length=10),
        ),
        migrations.AlterField(
            model_name='doggoaltarget',
            name='target_active_seconds',
            field=models.PositiveIntegerField(blank=True, help_text='Daily walking seconds. Leave empty to pause goals.', null=True),
        ),
    ]
