# Generated by Django 6.0.8 on 2026-10-09 15:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0007_personalised_goals'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='creation_fingerprint',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='dog',
            name='creation_request_id',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='doggoaltarget',
            name='request_id',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddConstraint(
            model_name='dog',
            constraint=models.UniqueConstraint(fields=('owner', 'creation_request_id'), name='dog_owner_request_unique'),
        ),
    ]
