# Generated by Django 6.0.8 on 2026-09-24 17:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '__first__'),
        ('rewards', '0004_pointentry_sources'),
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='venues.venue')),
                ('venue_name_snapshot', models.CharField(blank=True, max_length=100)),
                ('local_date', models.DateField()),
                ('category_slot', models.CharField(choices=[('CAFE', 'Café'), ('RESTAURANT', 'Restaurant'), ('PARK', 'Park'), ('VET', 'Vet')], max_length=16)),
                ('attempt_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('radius_m', models.PositiveIntegerField(default=20)),
                ('center_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('center_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('required_seconds', models.PositiveIntegerField()),
                ('verified_seconds', models.PositiveIntegerField(default=0)),
                ('last_recorded_at', models.DateTimeField(blank=True, null=True)),
                ('last_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('last_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('promised_points', models.PositiveIntegerField(default=12)),
                ('point_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rewards.pointentry')),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('rules_version', models.CharField(default='2026-09-24-v3', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['owner', 'collected_at'], name='checkin_owner_collection')],
                'constraints': [models.UniqueConstraint(fields=('owner', 'local_date', 'category_slot'), name='checkin_owner_day_slot_unique'), models.CheckConstraint(condition=models.Q(('category_slot__in', ['CAFE', 'RESTAURANT', 'PARK', 'VET'])), name='checkin_category_known'), models.CheckConstraint(condition=models.Q(('promised_points__gt', 0), ('radius_m__gt', 0), ('required_seconds__gt', 0)), name='checkin_positive_targets'), models.CheckConstraint(condition=models.Q(('verified_seconds__lte', models.F('required_seconds'))), name='checkin_progress_bounded'), models.CheckConstraint(condition=models.Q(('started_at__isnull', True), models.Q(('center_latitude__isnull', False), ('center_longitude__isnull', False), ('expires_at__gt', models.F('started_at')), ('venue__isnull', False)), _connector='OR'), name='checkin_started_shape'), models.CheckConstraint(condition=models.Q(('ready_at__isnull', True), models.Q(('started_at__isnull', False), ('verified_seconds', models.F('required_seconds'))), _connector='OR'), name='checkin_ready_shape'), models.CheckConstraint(condition=models.Q(('ready_at__isnull', True), models.Q(('ready_at__gte', models.F('started_at')), ('ready_at__lte', models.F('expires_at')), ('started_at__isnull', False)), _connector='OR'), name='checkin_ready_time_valid'), models.CheckConstraint(condition=models.Q(models.Q(('collected_at__isnull', True), ('point_entry__isnull', True)), models.Q(('collected_at__isnull', False), ('point_entry__isnull', False), ('ready_at__isnull', False)), _connector='OR'), name='checkin_collection_shape'), models.CheckConstraint(condition=models.Q(('collected_at__isnull', True), models.Q(('collected_at__gte', models.F('ready_at')), ('collected_at__lt', models.F('expires_at')), ('ready_at__isnull', False)), _connector='OR'), name='checkin_collection_time_valid'), models.CheckConstraint(condition=models.Q(('center_latitude__isnull', True), models.Q(('center_latitude__gte', -90), ('center_latitude__lte', 90)), _connector='OR'), name='checkin_latitude_range'), models.CheckConstraint(condition=models.Q(('center_longitude__isnull', True), models.Q(('center_longitude__gte', -180), ('center_longitude__lte', 180)), _connector='OR'), name='checkin_longitude_range')],
            },
        ),
    ]
