# Generated by Django 6.0.9 on 2026-10-09 04:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkins', '0001_initial'),
        ('rewards', '0004_pointentry_sources'),
        ('venues', '0002_venue_import_source'),
        ('walks', '0006_remove_checkin_location_samples'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckInWalk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField()),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('state', models.CharField(choices=[('RECORDING', 'Recording'), ('PAUSED', 'Paused'), ('FINISHED', 'Finished'), ('CANCELLED', 'Cancelled')], max_length=12)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='checkin',
            name='checkin_owner_day_slot_unique',
        ),
        migrations.RemoveConstraint(
            model_name='checkin',
            name='checkin_collection_time_valid',
        ),
        migrations.AddField(
            model_name='checkin',
            name='last_sequence',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkinwalk',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checkinwalk',
            name='walk',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checkin_context', to='walks.walk'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='walk_context',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checkins', to='checkins.checkinwalk'),
        ),
        migrations.AddConstraint(
            model_name='checkin',
            constraint=models.UniqueConstraint(fields=('walk_context', 'venue'), name='checkin_walk_venue_unique'),
        ),
        migrations.AddConstraint(
            model_name='checkin',
            constraint=models.CheckConstraint(condition=models.Q(('collected_at__isnull', True), models.Q(('collected_at__gte', models.F('ready_at')), ('ready_at__isnull', False)), _connector='OR'), name='checkin_collection_time_valid'),
        ),
        migrations.AddConstraint(
            model_name='checkinwalk',
            constraint=models.UniqueConstraint(fields=('owner', 'request_id'), name='checkin_walk_request_unique'),
        ),
        migrations.AddConstraint(
            model_name='checkinwalk',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('ended_at__isnull', True), ('state__in', ('RECORDING', 'PAUSED'))), models.Q(('ended_at__gte', models.F('started_at')), ('ended_at__isnull', False), ('state__in', ('FINISHED', 'CANCELLED'))), _connector='OR'), name='checkin_walk_state_shape'),
        ),
        migrations.AddConstraint(
            model_name='checkinwalk',
            constraint=models.CheckConstraint(condition=models.Q(('settled_at__isnull', True), models.Q(('state', 'FINISHED'), ('walk__isnull', False)), _connector='OR'), name='checkin_walk_settled_shape'),
        ),
    ]
