# Generated by Django 6.0.9 on 2026-10-09 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkins', '0002_checkinwalk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='last_captured_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkin',
            name='last_sample_fingerprint',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
