# Generated by Django 6.0.8 on 2026-09-07 11:51

import django.db.models.deletion
import redemptions.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("venues", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CafeOrderEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cursor", models.PositiveBigIntegerField()),
                ("venue_id", models.PositiveBigIntegerField()),
                ("order_id", models.PositiveBigIntegerField()),
                (
                    "kind",
                    models.CharField(
                        choices=[("UPSERT", "Upsert"), ("REMOVE", "Remove")],
                        max_length=6,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("id",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("venue_id", "cursor"),
                        name="cafe_order_event_venue_cursor_unique",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RedemptionOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        default=redemptions.models.generate_reference_number,
                        editable=False,
                        max_length=16,
                        unique=True,
                    ),
                ),
                (
                    "owner_name_snapshot",
                    models.CharField(blank=True, editable=False, max_length=100),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("COLLECTED", "Collected"),
                            ("EXPIRED", "Expired"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("total_points", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("collected_at", models.DateTimeField(blank=True, null=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        default=redemptions.models.next_local_midnight
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        limit_choices_to={"role": "OWNER"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="redemption_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="redemption_orders",
                        to="venues.venue",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="RedemptionOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_name_snapshot",
                    models.CharField(blank=True, editable=False, max_length=150),
                ),
                (
                    "point_price_snapshot",
                    models.PositiveIntegerField(default=0, editable=False),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="redemptions.redemptionorder",
                    ),
                ),
                (
                    "venue_offer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="redemption_order_items",
                        to="venues.venueoffer",
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
            },
        ),
        migrations.AddIndex(
            model_name="redemptionorder",
            index=models.Index(
                fields=["venue", "status", "created_at"],
                name="redemption_venue_feed_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="redemptionorder",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_points__gt", 0)),
                name="redemption_total_points_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="redemptionorderitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("point_price_snapshot__gt", 0)),
                name="redemption_item_price_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="redemptionorderitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)),
                name="redemption_item_quantity_positive",
            ),
        ),
    ]
