# Generated by Django 6.0.8 on 2026-08-26 07:36

import django.core.validators
import django.db.models.deletion
import rewards.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('point_cost', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cafe_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rewards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('cafe_user__display_name', 'point_cost', 'name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Redemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(default=rewards.models.new_redemption_reference, editable=False, max_length=20, unique=True)),
                ('reward_name_snapshot', models.CharField(max_length=100)),
                ('point_cost_snapshot', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COLLECTED', 'Collected'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(default=rewards.models.default_redemption_expiry)),
                ('owner_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to=settings.AUTH_USER_MODEL)),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='rewards.reward')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='PointEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('remaining_points', models.PositiveIntegerField(default=0)),
                ('type', models.CharField(choices=[('EARN', 'Earn'), ('SPEND', 'Spend'), ('REFUND', 'Refund'), ('EXPIRE', 'Expire'), ('ADMIN', 'Admin grant')], default='ADMIN', max_length=10)),
                ('source_reference', models.CharField(blank=True, help_text='Stable idempotency key for the event that created this entry.', max_length=120, null=True, unique=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at', 'id'),
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('amount__gt', 0), ('expires_at__isnull', False), ('type__in', ['EARN', 'REFUND', 'ADMIN']), ('remaining_points__lte', models.F('amount'))), models.Q(('amount__lt', 0), ('expires_at__isnull', True), ('remaining_points', 0), ('type__in', ['SPEND', 'EXPIRE'])), _connector='OR'), name='point_entry_credit_or_debit_shape')],
            },
        ),
        migrations.AddConstraint(
            model_name='reward',
            constraint=models.CheckConstraint(condition=models.Q(('point_cost__gt', 0)), name='reward_point_cost_positive'),
        ),
        migrations.AddConstraint(
            model_name='redemption',
            constraint=models.CheckConstraint(condition=models.Q(('point_cost_snapshot__gt', 0)), name='redemption_point_cost_positive'),
        ),
        migrations.AddConstraint(
            model_name='redemption',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('collected_at__isnull', False), ('status', 'COLLECTED')), models.Q(models.Q(('status', 'COLLECTED'), _negated=True), ('collected_at__isnull', True)), _connector='OR'), name='redemption_collected_timestamp_matches_status'),
        ),
    ]
