# Generated by Django 6.0.8 on 2026-09-24 16:58

from django.conf import settings
from django.db import migrations, models
from zoneinfo import ZoneInfo


def backfill_known_sources(apps, schema_editor):
    Entry = apps.get_model('rewards', 'PointEntry')
    alias = schema_editor.connection.alias
    melbourne = ZoneInfo('Australia/Melbourne')

    def classify(entry, category, day, version):
        Entry.objects.using(alias).filter(pk=entry.pk, type='EARN').update(
            earn_category=category, earned_on=day, rules_version=version)

    for walk in apps.get_model('walks', 'Walk').objects.using(alias).iterator():
        entry = Entry.objects.using(alias).filter(source_reference=f'walk:{walk.pk}', user_id=walk.owner_id, amount=walk.points_awarded, type='EARN').first()
        if entry:
            classify(entry, 'WALK', walk.point_date, 'walk-gps-v1')
    for award in apps.get_model('quests', 'QuestAward').objects.using(alias).select_related('point_entry').iterator():
        if award.point_entry.user_id == award.owner_id:
            classify(award.point_entry, 'BIRTHDAY', award.awarded_at.astimezone(melbourne).date(), award.rules_version)
    for entitlement in apps.get_model('evidence', 'DocumentEntitlement').objects.using(alias).filter(point_entry__isnull=False).select_related('point_entry').iterator():
        entry = entitlement.point_entry
        if entry.user_id == entitlement.owner_id:
            classify(entry, 'DOCUMENT', entry.created_at.astimezone(melbourne).date(), 'documents-2026-09-25')


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0003_venue_catalogue'),
        ('walks', '0001_initial'),
        ('quests', '0002_questaward'),
        ('evidence', '0002_documententitlement_collected_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pointentry',
            name='earn_category',
            field=models.CharField(blank=True, choices=[('WALK', 'Walk'), ('NET_WALK', 'Net-walking'), ('DAILY_GOAL', 'Daily goal'), ('CHECK_IN', 'Check-in'), ('STREAK', 'Streak'), ('BIRTHDAY', 'Birthday'), ('DOCUMENT', 'Document')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pointentry',
            name='earned_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pointentry',
            name='rules_version',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddIndex(
            model_name='pointentry',
            index=models.Index(fields=['user', 'expires_at'], name='points_owner_expiry'),
        ),
        migrations.AddIndex(
            model_name='pointentry',
            index=models.Index(fields=['user', 'earned_on', 'earn_category'], name='points_owner_day_source'),
        ),
        migrations.AddConstraint(
            model_name='pointentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('earn_category__isnull', True), ('earned_on__isnull', True), ('rules_version__isnull', True)), models.Q(('earn_category__in', ['WALK', 'NET_WALK', 'DAILY_GOAL', 'CHECK_IN', 'STREAK', 'BIRTHDAY', 'DOCUMENT']), ('earn_category__isnull', False), ('earned_on__isnull', False), ('rules_version__isnull', False), ('type', 'EARN'), models.Q(('rules_version', ''), _negated=True)), _connector='OR'), name='point_entry_earn_source_shape'),
        ),
        migrations.RunPython(backfill_known_sources, migrations.RunPython.noop),
    ]
