# Generated by Django 6.0.8 on 2026-09-24 15:20

import django.db.models.deletion
import evidence.storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dogs', '0003_dog_date_of_birth'),
        ('rewards', '0002_connected_redemptions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentEntitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_id_snapshot', models.PositiveBigIntegerField()),
                ('kind', models.CharField(choices=[('COUNCIL_REGISTRATION', 'Council registration'), ('MICROCHIP_REGISTRATION', 'Microchip registration'), ('VET_CHECKUP', 'Vet check-up')], max_length=30)),
                ('entitlement_key', models.CharField(max_length=80)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dogs.dog')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('point_entry', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='rewards.pointentry')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_id_snapshot', models.PositiveBigIntegerField()),
                ('dog_name_snapshot', models.CharField(max_length=100)),
                ('kind', models.CharField(choices=[('COUNCIL_REGISTRATION', 'Council registration'), ('MICROCHIP_REGISTRATION', 'Microchip registration'), ('VET_CHECKUP', 'Vet check-up')], max_length=30)),
                ('status', models.CharField(default='SELF_REPORTED', editable=False, max_length=20)),
                ('request_id', models.UUIDField()),
                ('request_fingerprint', models.CharField(max_length=64)),
                ('registration_number', models.CharField(blank=True, max_length=100)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('file', models.FileField(blank=True, max_length=200, storage=evidence.storage.PrivateEvidenceStorage(), upload_to='')),
                ('filename', models.CharField(blank=True, max_length=150)),
                ('file_content_type', models.CharField(blank=True, max_length=40)),
                ('file_sha256', models.CharField(blank=True, max_length=64)),
                ('awarded_points', models.PositiveIntegerField(default=0)),
                ('response_snapshot', models.JSONField(default=dict)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('dog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dogs.dog')),
                ('entitlement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evidence.documententitlement')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-submitted_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='EvidenceFingerprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('COUNCIL_REGISTRATION', 'Council registration'), ('MICROCHIP_REGISTRATION', 'Microchip registration'), ('VET_CHECKUP', 'Vet check-up')], max_length=30)),
                ('fingerprint', models.CharField(max_length=64)),
                ('dog_id_snapshot', models.PositiveBigIntegerField()),
                ('is_file', models.BooleanField()),
                ('entitlement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evidence.documententitlement')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='documententitlement',
            constraint=models.UniqueConstraint(fields=('dog_id_snapshot', 'kind', 'entitlement_key'), name='evidence_entitlement_unique'),
        ),
        migrations.AddConstraint(
            model_name='documentsubmission',
            constraint=models.UniqueConstraint(fields=('owner', 'request_id'), name='evidence_owner_request_unique'),
        ),
        migrations.AddConstraint(
            model_name='evidencefingerprint',
            constraint=models.UniqueConstraint(fields=('owner', 'dog_id_snapshot', 'kind', 'fingerprint'), name='evidence_fingerprint_unique'),
        ),
    ]
