# Generated by Django 6.0.8 on 2026-09-24 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def preserve_reward_values(apps, schema_editor):
    Entitlement = apps.get_model('evidence', 'DocumentEntitlement')
    values = {'COUNCIL_REGISTRATION': 300, 'MICROCHIP_REGISTRATION': 300, 'VET_CHECKUP': 200}
    for row in Entitlement.objects.using(schema_editor.connection.alias).select_related('point_entry').iterator():
        promised = row.point_entry.amount if row.point_entry_id else values[row.kind]
        Entitlement.objects.using(schema_editor.connection.alias).filter(pk=row.pk).update(promised_points=promised)


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0004_dog_daily_goal'),
        ('evidence', '0002_documententitlement_collected_at'),
        ('rewards', '0004_pointentry_sources'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documententitlement',
            name='eligibility_reason',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='documententitlement',
            name='eligibility_status',
            field=models.CharField(choices=[('ELIGIBLE', 'Eligible'), ('ON_HOLD', 'On hold'), ('REJECTED', 'Rejected')], default='ELIGIBLE', max_length=12),
        ),
        migrations.AddField(
            model_name='documententitlement',
            name='promised_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='documententitlement',
            name='rules_version',
            field=models.CharField(default='documents-2026-09-25', max_length=40),
        ),
        migrations.AddField(
            model_name='documentsubmission',
            name='audit_status',
            field=models.CharField(choices=[('NOT_REVIEWED', 'Not reviewed'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='NOT_REVIEWED', max_length=16),
        ),
        migrations.AddField(
            model_name='documentsubmission',
            name='file_size_bytes',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentsubmission',
            name='review_reason',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='documentsubmission',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentsubmission',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_evidence', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='documententitlement',
            index=models.Index(fields=['owner', 'collected_at'], name='evidence_owner_collection'),
        ),
        migrations.AddIndex(
            model_name='documententitlement',
            index=models.Index(fields=['dog_id_snapshot', 'kind', 'event_date'], name='evidence_dog_event'),
        ),
        migrations.RunPython(preserve_reward_values, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='documententitlement',
            constraint=models.CheckConstraint(condition=models.Q(('promised_points__gt', 0)), name='document_reward_positive'),
        ),
        migrations.AddConstraint(
            model_name='documententitlement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('collected_at__isnull', True), ('point_entry__isnull', True)), models.Q(('collected_at__isnull', False), ('point_entry__isnull', False)), _connector='OR'), name='document_collection_shape'),
        ),
        migrations.AddConstraint(
            model_name='documententitlement',
            constraint=models.CheckConstraint(condition=models.Q(('eligibility_status', 'ELIGIBLE'), models.Q(('eligibility_status__in', ('ON_HOLD', 'REJECTED')), models.Q(('eligibility_reason', ''), _negated=True)), _connector='OR'), name='document_eligibility_reason'),
        ),
    ]
