# Generated by Django 5.2.17 on 2026-09-01 00:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('venue_type', models.CharField(choices=[('VET', 'Vet'), ('DOG_PARK', 'Dog park'), ('CAFE', 'Café'), ('RESTAURANT', 'Restaurant'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('checkin_radius_m', models.PositiveIntegerField(default=50, help_text='Used by venue check-ins, not by redemption.')),
                ('required_dwell_s', models.PositiveIntegerField(default=0, help_text='Used by venue check-ins, not by redemption.')),
                ('opening_hours', models.CharField(blank=True, max_length=255)),
                ('photo', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, help_text='The CAFE account that signs in for this venue, if any.', limit_choices_to={'role': 'CAFE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staffed_venues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VenueOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('photo', models.URLField(blank=True)),
                ('point_price', models.PositiveIntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='venues.venue')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
