# Generated by Django 6.0.8 on 2026-09-28 23:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Venue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "venue_type",
                    models.CharField(
                        choices=[
                            ("VET", "Vet"),
                            ("DOG_PARK", "Dog park"),
                            ("CAFE", "Café"),
                            ("RESTAURANT", "Restaurant"),
                            ("OTHER", "Other"),
                        ],
                        max_length=12,
                    ),
                ),
                ("description", models.TextField(blank=True, max_length=2000)),
                ("address", models.CharField(blank=True, max_length=255)),
                ("opening_hours", models.CharField(blank=True, max_length=500)),
                (
                    "latitude",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(-90),
                            django.core.validators.MaxValueValidator(90),
                        ]
                    ),
                ),
                (
                    "longitude",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(-180),
                            django.core.validators.MaxValueValidator(180),
                        ]
                    ),
                ),
                (
                    "checkin_radius_m",
                    models.PositiveSmallIntegerField(
                        default=100,
                        help_text="Metres from the venue coordinate. Must exceed the 30 m GPS accuracy floor.",
                        validators=[
                            django.core.validators.MinValueValidator(30),
                            django.core.validators.MaxValueValidator(1000),
                        ],
                    ),
                ),
                (
                    "required_dwell_s",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Leave blank to use the default for the venue type (not available for Other).",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(60)],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("name", "id"),
            },
        ),
        migrations.CreateModel(
            name="CheckIn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IN_PROGRESS", "In progress"),
                            ("COMPLETED", "Completed"),
                            ("ABANDONED", "Abandoned"),
                        ],
                        default="IN_PROGRESS",
                        max_length=12,
                    ),
                ),
                (
                    "abandon_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LEFT_RADIUS", "Left the venue radius"),
                            ("SIGNAL_LOST", "Location reports stopped"),
                            ("SIMULATED", "Simulated location"),
                            ("CANCELLED", "Cancelled by the owner"),
                            ("REPLACED", "Replaced by a newer check-in"),
                        ],
                        max_length=12,
                    ),
                ),
                ("entered_at", models.DateTimeField()),
                ("last_report_at", models.DateTimeField()),
                ("dwell_completed_at", models.DateTimeField(blank=True, null=True)),
                ("awarded_points", models.PositiveSmallIntegerField(default=0)),
                ("completed_local_date", models.DateField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="check_ins",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="check_ins",
                        to="venues.venue",
                    ),
                ),
            ],
            options={
                "ordering": ("-entered_at", "-id"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("owner", "venue", "completed_local_date"),
                        name="checkin_owner_venue_date_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("completed_local_date__isnull", False),
                                ("dwell_completed_at__isnull", False),
                                ("status", "COMPLETED"),
                            ),
                            models.Q(
                                models.Q(("status", "COMPLETED"), _negated=True),
                                ("completed_local_date__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="checkin_completed_fields_match_status",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("awarded_points__lte", 12)),
                        name="checkin_points_at_most_12",
                    ),
                ],
            },
        ),
    ]
