# Generated by Django 6.0.8 on 2026-09-24 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_cafeprofile_google_maps_url_user_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_venue', to=settings.AUTH_USER_MODEL)),
                ('kind', models.CharField(choices=[('CAFE', 'Café'), ('RESTAURANT', 'Restaurant'), ('PARK', 'Park'), ('VET', 'Vet')], default='CAFE', max_length=16)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('photo', models.FileField(blank=True, max_length=255, upload_to='avatars/venues/')),
                ('address', models.CharField(blank=True, max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('opening_hours', models.CharField(blank=True, max_length=500)),
                ('google_maps_url', models.URLField(blank=True, max_length=2048)),
                ('is_partner', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('checkin_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name', 'id'),
                'indexes': [models.Index(fields=['is_active', 'kind'], name='venue_active_kind_idx'), models.Index(fields=['latitude', 'longitude'], name='venue_coordinates_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('latitude__isnull', True), ('longitude__isnull', True)), models.Q(('latitude__isnull', False), ('longitude__isnull', False)), _connector='OR'), name='venue_coordinates_paired'), models.CheckConstraint(condition=models.Q(('latitude__isnull', True), models.Q(('latitude__gte', -90), ('latitude__lte', 90)), _connector='OR'), name='venue_latitude_range'), models.CheckConstraint(condition=models.Q(('longitude__isnull', True), models.Q(('longitude__gte', -180), ('longitude__lte', 180)), _connector='OR'), name='venue_longitude_range'), models.CheckConstraint(condition=models.Q(('checkin_enabled', False), models.Q(('latitude__isnull', False), ('longitude__isnull', False)), _connector='OR'), name='venue_checkin_coordinates')],
            },
        ),
    ]
