# Generated by Django 6.0.8 on 2026-09-24 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def link_existing_base_credits(apps, schema_editor):
    Walk = apps.get_model("walks", "Walk")
    Entry = apps.get_model("rewards", "PointEntry")
    db = schema_editor.connection.alias
    for walk in Walk.objects.using(db).filter(points_awarded__gt=0, base_point_entry__isnull=True).iterator(chunk_size=500):
        entry = Entry.objects.using(db).filter(
            source_reference=f"walk:{walk.pk}", user_id=walk.owner_id,
            type="EARN", amount=walk.points_awarded,
        ).first()
        if entry is not None:
            Walk.objects.using(db).filter(pk=walk.pk).update(base_point_entry_id=entry.pk)
    # Unknown duration/name/net history remains null; no synthetic earnings.


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '__first__'),
        ('checkins', '0001_initial'),
        ('rewards', '0004_pointentry_sources'),
        ('walks', '0002_explicit_walk_dogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='walk',
            name='active_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walk',
            name='base_point_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='base_walk', to='rewards.pointentry'),
        ),
        migrations.AddField(
            model_name='walk',
            name='net_distance_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='walk',
            name='net_point_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='net_walk', to='rewards.pointentry'),
        ),
        migrations.AddField(
            model_name='walk',
            name='net_settled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walk',
            name='rules_version',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='walk',
            name='validation_summary',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.RunPython(link_existing_base_credits, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='walk',
            index=models.Index(fields=['owner', 'point_date'], name='walk_owner_point_date'),
        ),
        migrations.AddIndex(
            model_name='walk',
            index=models.Index(fields=['owner', 'ended_at'], name='walk_owner_ended_at'),
        ),
        migrations.AddConstraint(
            model_name='walk',
            constraint=models.CheckConstraint(condition=models.Q(('net_distance_m__isnull', True), ('net_distance_m__gte', 0), _connector='OR'), name='walk_net_distance_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='walk',
            constraint=models.CheckConstraint(condition=models.Q(('net_point_entry__isnull', True), models.Q(('net_distance_m__gt', 0), ('net_distance_m__isnull', False), ('net_settled_at__isnull', False)), _connector='OR'), name='walk_net_award_settled'),
        ),
        migrations.CreateModel(
            name='WalkSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='walk_sessions', to=settings.AUTH_USER_MODEL)),
                ('request_id', models.UUIDField()),
                ('walk', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='session', to='walks.walk')),
                ('state', models.CharField(choices=[('RECORDING', 'Recording'), ('PAUSED', 'Paused'), ('FINISHED', 'Finished'), ('TIMED_OUT', 'Timed out'), ('CANCELLED', 'Cancelled')], max_length=12)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('heartbeat_at', models.DateTimeField()),
                ('last_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('last_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('last_accuracy_m', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('location_recorded_at', models.DateTimeField(blank=True, null=True)),
                ('location_expires_at', models.DateTimeField(blank=True, null=True)),
                ('verified_active_seconds', models.PositiveIntegerField(default=0)),
                ('verified_distance_m', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_consent_at', models.DateTimeField(blank=True, null=True)),
                ('net_consent_withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('validation_version', models.CharField(max_length=40)),
            ],
            options={
                'indexes': [models.Index(fields=['state', 'heartbeat_at'], name='session_state_heartbeat'), models.Index(fields=['location_expires_at'], name='session_location_expiry')],
                'constraints': [models.UniqueConstraint(fields=('owner', 'request_id'), name='session_owner_request_unique'), models.CheckConstraint(condition=models.Q(models.Q(('ended_at__isnull', True), ('state__in', ('RECORDING', 'PAUSED'))), models.Q(('ended_at__gte', models.F('started_at')), ('ended_at__isnull', False), ('state__in', ('FINISHED', 'TIMED_OUT', 'CANCELLED'))), _connector='OR'), name='session_state_time_shape'), models.CheckConstraint(condition=models.Q(('verified_distance_m__gte', 0)), name='session_distance_nonnegative'), models.CheckConstraint(condition=models.Q(models.Q(('last_latitude__isnull', True), ('last_longitude__isnull', True)), models.Q(('last_latitude__gte', -90), ('last_latitude__isnull', False), ('last_latitude__lte', 90), ('last_longitude__gte', -180), ('last_longitude__isnull', False), ('last_longitude__lte', 180)), _connector='OR'), name='session_coordinates_valid'), models.CheckConstraint(condition=models.Q(models.Q(('location_expires_at__isnull', True), ('location_recorded_at__isnull', True)), models.Q(('location_expires_at__gt', models.F('location_recorded_at')), ('location_expires_at__isnull', False), ('location_recorded_at__isnull', False)), _connector='OR'), name='session_presence_expiry_valid'), models.CheckConstraint(condition=models.Q(('net_consent_withdrawn_at__isnull', True), models.Q(('net_consent_at__isnull', False), ('net_consent_withdrawn_at__gte', models.F('net_consent_at'))), _connector='OR'), name='session_consent_time_valid')],
            },
        ),
        migrations.CreateModel(
            name='LocationSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='location_samples', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='walks.walksession')),
                ('checkin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='checkins.checkin')),
                ('checkin_attempt_id', models.UUIDField(blank=True, null=True)),
                ('stream_id', models.UUIDField()),
                ('sequence', models.PositiveBigIntegerField()),
                ('segment_id', models.PositiveIntegerField()),
                ('recorded_at', models.DateTimeField()),
                ('received_at', models.DateTimeField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('accuracy_m', models.DecimalField(decimal_places=2, max_digits=7)),
                ('speed_mps', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('source_flags', models.JSONField(default=dict)),
                ('accepted', models.BooleanField(default=False)),
                ('rejection_reason', models.CharField(blank=True, max_length=80)),
            ],
            options={
                'indexes': [models.Index(fields=['owner', 'recorded_at'], name='sample_owner_time'), models.Index(fields=['session', 'recorded_at'], name='sample_session_time'), models.Index(fields=['checkin', 'recorded_at'], name='sample_checkin_time'), models.Index(fields=['received_at'], name='sample_received_at')],
                'constraints': [models.UniqueConstraint(fields=('owner', 'stream_id', 'sequence'), name='sample_stream_sequence_unique'), models.CheckConstraint(condition=models.Q(('session__isnull', False), ('checkin__isnull', False), _connector='OR'), name='sample_purpose_required'), models.CheckConstraint(condition=models.Q(models.Q(('checkin__isnull', True), ('checkin_attempt_id__isnull', True)), models.Q(('checkin__isnull', False), ('checkin_attempt_id__isnull', False)), _connector='OR'), name='sample_checkin_attempt_shape'), models.CheckConstraint(condition=models.Q(('latitude__gte', -90), ('latitude__lte', 90), ('longitude__gte', -180), ('longitude__lte', 180)), name='sample_coordinates_valid'), models.CheckConstraint(condition=models.Q(('accuracy_m__gte', 0)), name='sample_accuracy_nonnegative'), models.CheckConstraint(condition=models.Q(('speed_mps__isnull', True), ('speed_mps__gte', 0), _connector='OR'), name='sample_speed_nonnegative'), models.CheckConstraint(condition=models.Q(('accepted', False), ('rejection_reason', ''), _connector='OR'), name='sample_accepted_no_rejection')],
            },
        ),
        migrations.CreateModel(
            name='NetWalkInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_low', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='net_intervals_low', to='walks.walksession')),
                ('session_high', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='net_intervals_high', to='walks.walksession')),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField()),
                ('low_distance_m', models.DecimalField(decimal_places=2, max_digits=10)),
                ('high_distance_m', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rules_version', models.CharField(max_length=40)),
                ('validation_summary', models.JSONField(default=dict)),
                ('verified_at', models.DateTimeField()),
            ],
            options={
                'indexes': [models.Index(fields=['session_high', 'started_at'], name='net_high_session_time')],
                'constraints': [models.UniqueConstraint(fields=('session_low', 'session_high', 'started_at', 'ended_at'), name='net_interval_identity_unique'), models.CheckConstraint(condition=models.Q(('session_low__lt', models.F('session_high'))), name='net_session_pair_ordered'), models.CheckConstraint(condition=models.Q(('ended_at__gt', models.F('started_at'))), name='net_interval_end_after_start'), models.CheckConstraint(condition=models.Q(('high_distance_m__gte', 0), ('low_distance_m__gte', 0)), name='net_distances_nonnegative')],
            },
        ),
    ]
