# Generated by Django 6.0.8 on 2026-10-07 17:10

from django.conf import settings
from django.db import migrations, models


def normalize_sample_purpose(apps, schema_editor):
    LocationSample = apps.get_model('walks', 'LocationSample')
    samples = LocationSample.objects.using(schema_editor.connection.alias)
    # A check-in reference is the more specific purpose and carries its attempt
    # identity, so retain it if legacy data accidentally populated both fields.
    samples.filter(session__isnull=False, checkin__isnull=False).update(session=None)


class Migration(migrations.Migration):

    dependencies = [
        ('checkins', '0001_initial'),
        ('walks', '0003_activity_foundations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='locationsample',
            name='sample_purpose_required',
        ),
        migrations.RunPython(normalize_sample_purpose, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='locationsample',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('checkin__isnull', True), ('session__isnull', False)), models.Q(('checkin__isnull', False), ('session__isnull', True)), _connector='OR'), name='sample_single_purpose'),
        ),
    ]
