# Generated by Django 6.0.8 on 2026-10-07 17:18

import django.db.models.deletion
from django.db import migrations, models


def link_existing_intervals(apps, schema_editor):
    Interval = apps.get_model('walks', 'NetWalkInterval')
    Invitation = apps.get_model('social', 'NetWalkInvitation')
    for interval in Interval.objects.filter(invitation__isnull=True).iterator():
        invitation_id = (interval.validation_summary or {}).get('invitation_id')
        if not invitation_id:
            continue
        invitation = Invitation.objects.filter(pk=invitation_id).only(
            'id', 'sender_session_id', 'recipient_session_id'
        ).first()
        if invitation and {
            invitation.sender_session_id, invitation.recipient_session_id,
        } == {interval.session_low_id, interval.session_high_id}:
            Interval.objects.filter(pk=interval.pk).update(invitation_id=invitation.pk)


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_netwalkinvitation_net_invitation_status_time_shape'),
        ('walks', '0004_remove_locationsample_sample_purpose_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='netwalkinterval',
            name='invitation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verified_intervals', to='social.netwalkinvitation'),
        ),
        migrations.RunPython(link_existing_intervals, migrations.RunPython.noop),
    ]
