# Generated by Django 6.0.8 on 2026-10-07 17:44

import django.db.models.deletion
from django.db import migrations, models


def remove_legacy_checkin_samples(apps, schema_editor):
    """Check-ins keep only their current server-timed progress and latest fix."""
    LocationSample = apps.get_model('walks', 'LocationSample')
    LocationSample.objects.using(schema_editor.connection.alias).filter(
        session__isnull=True,
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('walks', '0005_netwalkinterval_invitation'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='locationsample',
            name='sample_checkin_attempt_shape',
        ),
        migrations.RemoveConstraint(
            model_name='locationsample',
            name='sample_single_purpose',
        ),
        migrations.RemoveIndex(
            model_name='locationsample',
            name='sample_checkin_time',
        ),
        migrations.RunPython(remove_legacy_checkin_samples, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='locationsample',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='walks.walksession'),
        ),
        migrations.RemoveField(
            model_name='locationsample',
            name='checkin',
        ),
        migrations.RemoveField(
            model_name='locationsample',
            name='checkin_attempt_id',
        ),
    ]
