# Generated by Django 6.0.8 on 2026-09-24 17:01

import django.db.models.deletion
import django.utils.timezone
import rewards.policy
from django.conf import settings
from django.db import migrations, models
from zoneinfo import ZoneInfo


def backfill_qualifications(apps, schema_editor):
    Award = apps.get_model('quests', 'QuestAward')
    for award in Award.objects.using(schema_editor.connection.alias).select_related('point_entry').iterator():
        Award.objects.using(schema_editor.connection.alias).filter(pk=award.pk).update(
            qualification_key=f'birthday:{award.dog_id_snapshot}:{award.year}',
            qualified_at=award.awarded_at,
            qualified_on=award.awarded_at.astimezone(ZoneInfo('Australia/Melbourne')).date(),
            promised_points=award.point_entry.amount,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0004_dog_daily_goal'),
        ('quests', '0002_questaward'),
        ('rewards', '0004_pointentry_sources'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='questaward',
            name='claim_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questaward',
            name='eligibility_snapshot',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='questaward',
            name='milestone_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questaward',
            name='promised_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questaward',
            name='qualification_key',
            field=models.CharField(max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='questaward',
            name='qualified_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='questaward',
            name='qualified_on',
            field=models.DateField(default=rewards.policy.local_date),
        ),
        migrations.AddField(
            model_name='questaward',
            name='run_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questaward',
            name='awarded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questaward',
            name='dog_id_snapshot',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questaward',
            name='dog_name_snapshot',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='questaward',
            name='kind',
            field=models.CharField(choices=[('BIRTHDAY', 'Birthday'), ('DAILY_GOAL', 'Daily goal'), ('STREAK', 'Streak')], max_length=20),
        ),
        migrations.AlterField(
            model_name='questaward',
            name='point_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quest_award', to='rewards.pointentry'),
        ),
        migrations.AlterField(
            model_name='questaward',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='questaward',
            index=models.Index(fields=['owner', 'awarded_at'], name='quest_owner_collection'),
        ),
        migrations.RunPython(backfill_qualifications, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='questaward', name='qualification_key',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AddConstraint(
            model_name='questaward',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('qualification_key', ''), _negated=True), ('promised_points__gt', 0)), name='quest_qualification_required'),
        ),
        migrations.AddConstraint(
            model_name='questaward',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('awarded_at__isnull', True), ('point_entry__isnull', True)), models.Q(('awarded_at__isnull', False), ('point_entry__isnull', False)), _connector='OR'), name='quest_collection_shape'),
        ),
        migrations.AddConstraint(
            model_name='questaward',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('dog_id_snapshot__isnull', False), ('kind', 'BIRTHDAY'), ('milestone_days__isnull', True), ('run_start_date__isnull', True), ('year__isnull', False)), models.Q(('dog_id_snapshot__isnull', True), ('kind', 'DAILY_GOAL'), ('milestone_days__isnull', True), ('run_start_date__isnull', True), ('year__isnull', True)), models.Q(('dog_id_snapshot__isnull', True), ('kind', 'STREAK'), ('milestone_days__gt', 0), ('milestone_days__isnull', False), ('run_start_date__isnull', False), ('year__isnull', True)), _connector='OR'), name='quest_kind_shape'),
        ),
    ]
