# Generated by Django 6.0.8 on 2026-10-09 15:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0008_dog_creation_fingerprint_dog_creation_request_id_and_more'),
        ('quests', '0003_typed_qualifications'),
        ('rewards', '0004_pointentry_sources'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='questaward',
            constraint=models.UniqueConstraint(fields=('kind', 'dog_id_snapshot', 'qualified_on'), name='quest_award_dog_day_unique'),
        ),
        migrations.RemoveConstraint(
            model_name='questaward',
            name='quest_kind_shape',
        ),
        migrations.AddConstraint(
            model_name='questaward',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('dog_id_snapshot__isnull', False), ('kind', 'BIRTHDAY'), ('milestone_days__isnull', True), ('run_start_date__isnull', True), ('year__isnull', False)), models.Q(('kind', 'DAILY_GOAL'), ('milestone_days__isnull', True), ('run_start_date__isnull', True), ('year__isnull', True)), models.Q(('dog_id_snapshot__isnull', True), ('kind', 'STREAK'), ('milestone_days__gt', 0), ('milestone_days__isnull', False), ('run_start_date__isnull', False), ('year__isnull', True)), _connector='OR'), name='quest_kind_shape'),
        ),
    ]
