# Generated by Django 6.0.8 on 2026-09-24 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_low', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships_low', to=settings.AUTH_USER_MODEL)),
                ('user_high', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships_high', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_requests_sent', to=settings.AUTH_USER_MODEL)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['user_high', 'status'], name='friendship_high_status')],
                'constraints': [models.UniqueConstraint(fields=('user_low', 'user_high'), name='friendship_pair_unique'), models.CheckConstraint(condition=models.Q(('user_low__lt', models.F('user_high'))), name='friendship_pair_ordered'), models.CheckConstraint(condition=models.Q(('requested_by', models.F('user_low')), ('requested_by', models.F('user_high')), _connector='OR'), name='friendship_requester_in_pair'), models.CheckConstraint(condition=models.Q(models.Q(('responded_at__isnull', True), ('status', 'PENDING')), models.Q(('responded_at__isnull', False), ('status__in', ('ACCEPTED', 'DECLINED'))), _connector='OR'), name='friendship_response_shape')],
            },
        ),
        migrations.CreateModel(
            name='UserBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks_created', to=settings.AUTH_USER_MODEL)),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks_received', to=settings.AUTH_USER_MODEL)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['blocked', 'blocker'], name='user_block_reverse')],
                'constraints': [models.UniqueConstraint(fields=('blocker', 'blocked'), name='user_block_pair_unique'), models.CheckConstraint(condition=models.Q(('blocker', models.F('blocked')), _negated=True), name='user_block_not_self')],
            },
        ),
    ]
