# Generated by Django 6.0.8 on 2026-10-07 17:10

from datetime import timedelta

from django.conf import settings
from django.db import migrations, models


def normalize_invitation_states(apps, schema_editor):
    Invitation = apps.get_model('social', 'NetWalkInvitation')
    rows = Invitation.objects.using(schema_editor.connection.alias)
    terminal = ('DECLINED', 'EXPIRED', 'CANCELLED')
    known = ('PENDING', 'ACTIVE', 'ENDED', *terminal)

    # Canonicalize even malformed legacy rows. Accepted consent wins over a
    # pending label, and an end timestamp always makes that consent terminal.
    rows.filter(
        status='PENDING', accepted_at__isnull=False, ended_at__isnull=False,
    ).update(status='ENDED')
    rows.filter(
        status='PENDING', accepted_at__isnull=True, ended_at__isnull=False,
    ).update(status='CANCELLED')
    rows.filter(
        status='PENDING', accepted_at__isnull=False, ended_at__isnull=True,
    ).update(status='ACTIVE')

    # An ACTIVE row represents accepted consent. If it already has an end,
    # retain the accepted event and finalize it as ENDED.
    rows.filter(status='ACTIVE', accepted_at__isnull=True).update(
        accepted_at=models.F('created_at')
    )
    rows.filter(status='ACTIVE', ended_at__isnull=False).update(status='ENDED')

    # ENDED without acceptance was only a cancelled pending request. Accepted
    # terminal rows missing their timestamp end at their acceptance fallback.
    rows.filter(status='ENDED', accepted_at__isnull=True).update(status='CANCELLED')
    rows.filter(status='ENDED', ended_at__isnull=True).update(
        ended_at=models.F('accepted_at')
    )
    rows.filter(
        status__in=terminal, accepted_at__isnull=False, ended_at__isnull=True,
    ).update(ended_at=models.F('accepted_at'))
    rows.filter(status__in=terminal, accepted_at__isnull=False).update(status='ENDED')
    rows.filter(status__in=terminal, ended_at__isnull=True).update(
        ended_at=models.F('created_at')
    )

    # Choices were previously application-only, so make unexpected labels fit
    # the same safe terminal shapes instead of failing the new DB constraint.
    unknown = rows.exclude(status__in=known)
    unknown.filter(accepted_at__isnull=False, ended_at__isnull=True).update(
        ended_at=models.F('accepted_at')
    )
    unknown.filter(accepted_at__isnull=False).update(status='ENDED')
    unknown.filter(accepted_at__isnull=True, ended_at__isnull=True).update(
        ended_at=models.F('created_at')
    )
    unknown.filter(accepted_at__isnull=True).update(status='CANCELLED')

    # Clamp legacy timestamps to the first valid instant rather than discarding
    # an invitation or inventing an ordering. Expiry must remain strictly after
    # creation so a malformed pending row gets a short, deterministic window.
    rows.filter(expires_at__lte=models.F('created_at')).update(
        expires_at=models.F('created_at') + timedelta(seconds=1)
    )
    rows.filter(accepted_at__lt=models.F('created_at')).update(
        accepted_at=models.F('created_at')
    )
    rows.filter(
        accepted_at__isnull=False, ended_at__lt=models.F('accepted_at'),
    ).update(ended_at=models.F('accepted_at'))
    rows.filter(
        accepted_at__isnull=True, ended_at__lt=models.F('created_at'),
    ).update(ended_at=models.F('created_at'))


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_stable_invitation_foreign_key_indexes'),
        ('walks', '0003_activity_foundations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(normalize_invitation_states, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='netwalkinvitation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('accepted_at__isnull', True), ('ended_at__isnull', True), ('status', 'PENDING')), models.Q(('accepted_at__isnull', False), ('ended_at__isnull', True), ('status', 'ACTIVE')), models.Q(('accepted_at__isnull', False), ('ended_at__isnull', False), ('status', 'ENDED')), models.Q(('accepted_at__isnull', True), ('ended_at__isnull', False), ('status__in', ('DECLINED', 'EXPIRED', 'CANCELLED'))), _connector='OR'), name='net_invitation_status_time_shape'),
        ),
        migrations.AddConstraint(
            model_name='netwalkinvitation',
            constraint=models.CheckConstraint(condition=models.Q(('expires_at__gt', models.F('created_at'))), name='net_invitation_expiry_after_create'),
        ),
        migrations.AddConstraint(
            model_name='netwalkinvitation',
            constraint=models.CheckConstraint(condition=models.Q(('accepted_at__isnull', True), ('accepted_at__gte', models.F('created_at')), _connector='OR'), name='net_invitation_accept_after_create'),
        ),
        migrations.AddConstraint(
            model_name='netwalkinvitation',
            constraint=models.CheckConstraint(condition=models.Q(('ended_at__isnull', True), models.Q(('accepted_at__isnull', False), ('ended_at__gte', models.F('accepted_at'))), models.Q(('accepted_at__isnull', True), ('ended_at__gte', models.F('created_at'))), _connector='OR'), name='net_invitation_end_chronological'),
        ),
    ]
