# Generated by Django 5.2.17 on 2026-09-01 00:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('redemptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PointLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('WALK', 'Walk'), ('GOAL', 'Daily goal'), ('CHECKIN', 'Venue check-in'), ('VET', 'Vet checkup'), ('COUNCIL', 'Council registration'), ('STREAK', 'Streak bonus'), ('REFUND', 'Redemption refund'), ('ADMIN_GRANT', 'Admin grant (dev/testing)')], max_length=20)),
                ('amount_earned', models.PositiveIntegerField()),
                ('amount_remaining', models.PositiveIntegerField()),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_lots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['expires_at', 'earned_at'],
            },
        ),
        migrations.CreateModel(
            name='PointLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(help_text='Signed: positive earns, negative spends.')),
                ('entry_type', models.CharField(choices=[('WALK', 'Walk'), ('GOAL', 'Daily goal'), ('CHECKIN', 'Venue check-in'), ('VET', 'Vet checkup'), ('COUNCIL', 'Council registration'), ('STREAK', 'Streak bonus'), ('ADMIN_GRANT', 'Admin grant (dev/testing)'), ('REDEMPTION_SPEND', 'Redemption spend'), ('REDEMPTION_REFUND', 'Redemption refund')], max_length=20)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_ledger_entries', to=settings.AUTH_USER_MODEL)),
                ('redemption_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='redemptions.redemptionorder')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='wallets.pointlot')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
